# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-143116577-1'

menu:
# - {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
# - {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
# - {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Support', folder: 'pages', file: 'support.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/jradavenport'}
- {icon: 'youtube-play', link: 'http://youtube.com/james-davenport'}
- {icon: 'github', link: 'https://github.com/jradavenport'}
- {icon: 'instagram', link: 'https://instagram.com/jradavenport'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share this!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Published'
